import 'package:nutri_mvp/core/result.dart';

import '../entities/food_item.dart';
import '../failures/nutrition_failure.dart';

/// Domain port for loading the food composition table.
///
/// Separate from [DietPlanStore] because the table is READ-ONLY reference data
/// shipped with the app, not user state: it is regenerated by a build tool, has
/// its own licence and provenance, and never changes at runtime.
abstract interface class FoodTableSource {
  /// Every food the app knows about, before any plan-specific recipes are
  /// layered on top.
  Future<Result<List<FoodItem>, NutritionFailure>> loadFoods();
}
