import 'package:flutter/services.dart';
import 'package:nutri_mvp/core/result.dart';
import 'package:nutri_mvp/features/nutrition/data/codecs/food_table_codec.dart';
import 'package:nutri_mvp/features/nutrition/domain/entities/food_item.dart';
import 'package:nutri_mvp/features/nutrition/domain/failures/nutrition_failure.dart';
import 'package:nutri_mvp/features/nutrition/domain/ports/food_table_source.dart';

/// Loads the food table from the bundled asset generated by
/// `tool/build_food_table.py`.
///
/// The decoded result is cached for the lifetime of this instance: the table is
/// immutable reference data of a few dozen kilobytes, and re-parsing it on every
/// day view would be pure waste.
class AssetFoodTableSource implements FoodTableSource {
  AssetFoodTableSource({
    AssetBundle? bundle,
    this.assetKey = defaultAssetKey,
    FoodTableCodec codec = const FoodTableCodec(),
  })  : _bundle = bundle ?? rootBundle,
        _codec = codec;

  static const String defaultAssetKey = 'assets/nutrition/food_table.json';

  final AssetBundle _bundle;
  final String assetKey;
  final FoodTableCodec _codec;

  List<FoodItem>? _cached;

  @override
  Future<Result<List<FoodItem>, NutritionFailure>> loadFoods() async {
    final cached = _cached;
    if (cached != null) return Ok(cached);

    final String source;
    try {
      source = await _bundle.loadString(assetKey);
    } catch (e) {
      // A missing or unreadable asset is an availability problem, not a
      // malformed-data one: the bytes never arrived.
      return Err(StorageFailure('Could not read $assetKey: $e'));
    }

    final decoded = _codec.decode(source);
    if (decoded case Ok(value: final foods)) {
      _cached = foods;
    }
    return decoded;
  }
}
