import 'dart:convert';

import 'package:nutri_mvp/core/result.dart';

import '../../domain/entities/food_item.dart';
import '../../domain/failures/nutrition_failure.dart';
import '../../domain/value_objects/energy.dart';
import '../../domain/value_objects/macros.dart';
import '../../domain/value_objects/nutrition_target.dart';
import 'json_reader.dart';

/// Reads the bundled food composition table (`assets/nutrition/food_table.json`,
/// generated by `tool/build_food_table.py`) into [FoodItem]s.
class FoodTableCodec {
  const FoodTableCodec();

  /// The only schema version this codec understands.
  static const int supportedSchemaVersion = 1;

  Result<List<FoodItem>, NutritionFailure> decode(String source) {
    final Object? raw;
    try {
      raw = jsonDecode(source);
    } on FormatException catch (error) {
      return Err(MalformedPlanFailure('food table is not valid JSON: '
          '${error.message}'));
    }

    try {
      final root = JsonReader.object(raw, 'food table');
      final version = root.integer('schemaVersion');
      if (version != supportedSchemaVersion) {
        return Err(MalformedPlanFailure(
          'unsupported food table schemaVersion $version, '
          'expected $supportedSchemaVersion',
        ));
      }
      return Ok([
        for (final entry in root.objectList('foods')) _food(entry),
      ]);
    } on JsonReadException catch (error) {
      return Err(MalformedPlanFailure(error.message));
    }
  }

  static FoodItem _food(JsonReader reader) {
    final per100g = reader.child('per100g');
    return FoodItem(
      id: reader.string('id'),
      name: reader.string('nameEs'),
      preparation: FoodPreparation.parse(reader.string('preparation')),
      per100g: NutritionTarget(
        energy: Energy(kcal: per100g.number('energyKcal')),
        macros: Macros(
          proteinG: per100g.number('proteinG'),
          carbsG: per100g.number('carbsG'),
          fatG: per100g.number('fatG'),
        ),
      ),
      source: _source(reader.string('source'), reader.path),
      sourceRef: reader.stringOrNull('sourceRef'),
    );
  }

  static FoodDataSource _source(String raw, String path) => switch (raw) {
    'usda_sr_legacy' => FoodDataSource.usdaSrLegacy,
    'plan_recipe' => FoodDataSource.planRecipe,
    'estimated' => FoodDataSource.estimated,
    _ => throw JsonReadException('$path.source: unknown source "$raw"'),
  };
}
